[toolchain]
channel = "1.78.0"
components = [
    "rustfmt",
    "clippy",
    "rust-src",
    "llvm-tools-preview",
    "rust-analyzer",
]
targets = [
    "x86_64-unknown-linux-musl",
    # use below one for arm
    # "armv7-unknown-linux-gnueabihf",
]
